package com.rfsat.shimmerenact.data.repository

import android.content.Context
import android.os.Environment
import com.rfsat.shimmerenact.data.models.LocationPoint
import com.rfsat.shimmerenact.data.models.ShimmerSample
import com.rfsat.shimmerenact.data.models.ShimmerSignal
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.BufferedWriter
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class RecordingRepository(private val context: Context) {

    private var writer: BufferedWriter? = null
    private var currentFile: File? = null
    private var headerWritten = false
    private var sampleCount = 0L

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
    private val isoFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

    // ─── Start a new recording session ───────────────────────────────────────
    fun lastSession(): RecordingSession? {
        return try {
            val downloads = android.os.Environment.getExternalStoragePublicDirectory(
                android.os.Environment.DIRECTORY_DOWNLOADS)
            val root = java.io.File(downloads, "ShimmerENACT")
            if (!root.exists()) return null
            val dir = root.listFiles { f -> f.isDirectory }
                ?.maxByOrNull { it.lastModified() } ?: return null
            RecordingSession(
                sessionId    = dir.name,
                deviceName   = dir.name,
                startTimeMs  = dir.lastModified(),
                files        = dir.listFiles { f: java.io.File -> f.extension == "csv" }
                    ?.map { f -> RecordingFile(f.nameWithoutExtension, f.absolutePath, f.length(), f.lastModified()) }
                    ?: emptyList()
            )
        } catch (_: Exception) { null }
    }

        suspend fun startRecording(
        deviceName: String,
        signals: List<ShimmerSignal>,
        append: Boolean = false
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val dir = getRecordingDir()
            val ts = dateFormat.format(Date())
            val safeName = deviceName.replace(Regex("[^A-Za-z0-9_-]"), "_")
            val file = File(dir, "shimmer_${safeName}_$ts.csv")
            currentFile = file
            writer = BufferedWriter(FileWriter(file))

            // Write CSV header
            val header = buildString {
                append("timestamp_iso,timestamp_ms")
                signals.forEach { sig -> append(",${sig.key}_${sig.unit.replace("/","per")}") }
                // Add metadata comment line
            }
            writer?.write("# RFSAT Limited - ENACT Project (Horizon Europe Grant 101157151)\n")
            writer?.write("# Device: $deviceName\n")
            writer?.write("# Session start: ${isoFormat.format(Date())}\n")
            writer?.write("# Generated by ShimmerENACT v1.0\n")
            writer?.write(header + "\n")
            headerWritten = true
            sampleCount = 0L

            Result.success(file.absolutePath)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // ─── Write a single sample ────────────────────────────────────────────────
    suspend fun writeSample(
        sample: ShimmerSample,
        signals: List<ShimmerSignal>,
        location: LocationPoint? = null
    ) = withContext(Dispatchers.IO) {
        if (!headerWritten || writer == null) return@withContext
        try {
            val row = buildString {
                append(isoFormat.format(Date(sample.timestampMs)))
                append(",")
                append(sample.timestampMs)
                signals.forEach { sig ->
                    append(",")
                    val v = sample.values[sig.key]
                    if (v != null) append("%.6f".format(v)) else append("")
                }
            }
            writer?.write(row + "\n")
            sampleCount++
            // Flush every 100 samples to keep data safe
            if (sampleCount % 100L == 0L) writer?.flush()
        } catch (_: Exception) {}
    }

    // ─── Stop recording ───────────────────────────────────────────────────────
    suspend fun stopRecording(): Result<Pair<String, Long>> = withContext(Dispatchers.IO) {
        try {
            writer?.write("# Session end: ${isoFormat.format(Date())}\n")
            writer?.write("# Total samples: $sampleCount\n")
            writer?.flush()
            writer?.close()
            writer = null
            headerWritten = false
            val path = currentFile?.absolutePath ?: ""
            val count = sampleCount
            sampleCount = 0L
            Result.success(Pair(path, count))
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // ─── List all recordings ──────────────────────────────────────────────────
    suspend fun listRecordings(): List<RecordingFile> = withContext(Dispatchers.IO) {
        getRecordingDir().listFiles { f -> f.extension == "csv" }
            ?.sortedByDescending { it.lastModified() }
            ?.map { f ->
                RecordingFile(
                    name = f.nameWithoutExtension,
                    path = f.absolutePath,
                    sizeBytes = f.length(),
                    lastModified = f.lastModified()
                )
            } ?: emptyList()
    }

    // ─── Delete a recording ───────────────────────────────────────────────────
    suspend fun deleteRecording(path: String): Boolean = withContext(Dispatchers.IO) {
        File(path).delete()
    }

    // ─── Directory helper ─────────────────────────────────────────────────────
    private fun getRecordingDir(): File {
        val dir = File(
            context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),
            "ShimmerENACT"
        )
        if (!dir.exists()) dir.mkdirs()
        return dir
    }

    val isRecording: Boolean get() = headerWritten && writer != null
    val currentSampleCount: Long get() = sampleCount
    val currentFilePath: String get() = currentFile?.absolutePath ?: ""
}

data class RecordingFile(
    val name: String,
    val path: String,
    val sizeBytes: Long,
    val lastModified: Long
) {
    val sizeDisplay: String get() = when {
        sizeBytes > 1_048_576 -> "%.1f MB".format(sizeBytes / 1_048_576.0)
        sizeBytes > 1024 -> "%.1f KB".format(sizeBytes / 1024.0)
        else -> "$sizeBytes B"
    }
}

data class RecordingSession(
    val sessionId: String,
    val deviceName: String,
    val startTimeMs: Long,
    val files: List<RecordingFile>
)
