package com.rfsat.shimmerenact.data.repository

import android.content.Context
import android.os.Environment
<<<<<<< HEAD
=======
import com.rfsat.shimmerenact.data.models.RateConstraints
>>>>>>> parent of 335abb6 (Added position)
import com.rfsat.shimmerenact.data.models.ShimmerSample
import com.rfsat.shimmerenact.data.models.ShimmerSignal
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.BufferedWriter
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

<<<<<<< HEAD
=======
// ─── Per-signal recording channel ─────────────────────────────────────────────

private data class SignalChannel(
    val signal: ShimmerSignal,
    val targetHz: Int,         // desired output rate
    val hardwareHz: Int,       // hardware stream rate
    val writer: BufferedWriter,
    val file: File
) {
    // Emit every Nth hardware sample to achieve targetHz
    val decimationStep: Int = (hardwareHz.toDouble() / targetHz.coerceAtLeast(1))
        .coerceAtLeast(1.0).toInt()
    var counter: Int = 0
    var rowsWritten: Long = 0L
}

// ─── Session metadata ─────────────────────────────────────────────────────────

data class RecordingSession(
    val sessionId: String,          // timestamp-based, same for all files in the session
    val deviceName: String,
    val startTimeMs: Long,
    val files: List<RecordingFile>  // one per signal
)

// ─── Repository ───────────────────────────────────────────────────────────────

>>>>>>> parent of 335abb6 (Added position)
class RecordingRepository(private val context: Context) {

    private var writer: BufferedWriter? = null
    private var currentFile: File? = null
    private var headerWritten = false
    private var sampleCount = 0L

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
    private val isoFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

<<<<<<< HEAD
    // ─── Start a new recording session ───────────────────────────────────────
    fun lastSession(): RecordingSession? {
        return try {
            val downloads = android.os.Environment.getExternalStoragePublicDirectory(
                android.os.Environment.DIRECTORY_DOWNLOADS)
            val root = java.io.File(downloads, "ShimmerENACT")
            if (!root.exists()) return null
            val dir = root.listFiles { f -> f.isDirectory }
                ?.maxByOrNull { it.lastModified() } ?: return null
            RecordingSession(
                sessionId    = dir.name,
                deviceName   = dir.name,
                startTimeMs  = dir.lastModified(),
                files        = dir.listFiles { f: java.io.File -> f.extension == "csv" }
                    ?.map { f -> RecordingFile(f.nameWithoutExtension, f.absolutePath, f.length(), f.lastModified()) }
                    ?: emptyList()
            )
        } catch (_: Exception) { null }
    }

        suspend fun startRecording(
        deviceName: String,
        signals: List<ShimmerSignal>
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val dir = getRecordingDir()
            val ts = dateFormat.format(Date())
            val safeName = deviceName.replace(Regex("[^A-Za-z0-9_-]"), "_")
            val file = File(dir, "shimmer_${safeName}_$ts.csv")
            currentFile = file
            writer = BufferedWriter(FileWriter(file))

            // Write CSV header
            val header = buildString {
                append("timestamp_iso,timestamp_ms")
                signals.forEach { sig -> append(",${sig.key}_${sig.unit.replace("/","per")}") }
                // Add metadata comment line
            }
            writer?.write("# RFSAT Limited - ENACT Project (Horizon Europe Grant 101157151)\n")
            writer?.write("# Device: $deviceName\n")
            writer?.write("# Session start: ${isoFormat.format(Date())}\n")
            writer?.write("# Generated by ShimmerENACT v1.0\n")
            writer?.write(header + "\n")
            headerWritten = true
            sampleCount = 0L

            Result.success(file.absolutePath)
=======
    val isRecording: Boolean get() = _isRecording
    val totalSamplesWritten: Long get() = _totalSamplesWritten
    val currentSessionId: String get() = sessionId
    val currentSessionDir: String get() = sessionDir?.absolutePath ?: ""

    // ─── Start recording — one file per selected signal ───────────────────────
    suspend fun startRecording(
        deviceName: String,
        signals: List<ShimmerSignal>,       // signals to record (already filtered to selection)
        signalRatesHz: Map<String, Int>,    // key → target Hz; missing = hardwareHz
        hardwareHz: Int
    ): Result<List<String>> = withContext(Dispatchers.IO) {
        if (_isRecording) stopRecording()
        try {
            sessionId = sessionDateFmt.format(Date())
            val safeName = deviceName.replace(Regex("[^A-Za-z0-9_-]"), "_")

            // Create a session sub-directory so all files from one recording session
            // are grouped together:  ShimmerENACT / session_YYYY-MM-DD_HH-mm-ss /
            val rootDir = getRootDir()
            val dir = File(rootDir, "${safeName}_$sessionId").also { it.mkdirs() }
            sessionDir = dir

            val startTs = isoFmt.format(Date())
            val paths = mutableListOf<String>()

            for (sig in signals) {
                val targetHz = (signalRatesHz[sig.key] ?: hardwareHz).coerceIn(1, hardwareHz)
                val safeKey = sig.key.replace(Regex("[^A-Za-z0-9_]"), "_")
                val file = File(dir, "${safeKey}.csv")
                val bw = BufferedWriter(FileWriter(file))

                // Header block
                bw.write("# RFSAT Limited — ENACT Project (Horizon Europe Grant 101157151)\n")
                bw.write("# Device: $deviceName\n")
                bw.write("# Signal: ${sig.displayName}  [${sig.unit}]\n")
                bw.write("# Hardware rate: $hardwareHz Hz  |  Output rate: $targetHz Hz\n")
                bw.write("# Session start: $startTs\n")
                bw.write("# Generated by ShimmerENACT v1.0\n")
                bw.write("timestamp_iso,timestamp_ms,${sig.key}_${sig.unit.replace("/", "per")}\n")

                channels.add(SignalChannel(sig, targetHz, hardwareHz, bw, file))
                paths.add(file.absolutePath)
            }

            _isRecording = true
            _totalSamplesWritten = 0L
            AppLog.ok("REC", "Session started — ${signals.size} files in ${dir.name}")
            Result.success(paths)
>>>>>>> parent of 335abb6 (Added position)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

<<<<<<< HEAD
    // ─── Write a single sample ────────────────────────────────────────────────
    suspend fun writeSample(
        sample: ShimmerSample,
        signals: List<ShimmerSignal>
    ) = withContext(Dispatchers.IO) {
        if (!headerWritten || writer == null) return@withContext
        try {
            val row = buildString {
                append(isoFormat.format(Date(sample.timestampMs)))
                append(",")
                append(sample.timestampMs)
                signals.forEach { sig ->
                    append(",")
                    val v = sample.values[sig.key]
                    if (v != null) append("%.6f".format(v)) else append("")
                }
            }
            writer?.write(row + "\n")
            sampleCount++
            // Flush every 100 samples to keep data safe
            if (sampleCount % 100L == 0L) writer?.flush()
        } catch (_: Exception) {}
    }

    // ─── Stop recording ───────────────────────────────────────────────────────
    suspend fun stopRecording(): Result<Pair<String, Long>> = withContext(Dispatchers.IO) {
        try {
            writer?.write("# Session end: ${isoFormat.format(Date())}\n")
            writer?.write("# Total samples: $sampleCount\n")
            writer?.flush()
            writer?.close()
            writer = null
            headerWritten = false
            val path = currentFile?.absolutePath ?: ""
            val count = sampleCount
            sampleCount = 0L
            Result.success(Pair(path, count))
=======
    // ─── Write a hardware sample — applies per-channel decimation ─────────────
    fun writeSampleSync(sample: ShimmerSample) {
        if (!_isRecording || channels.isEmpty()) return
        val isoTs = isoFmt.format(Date(sample.timestampMs))
        var wrote = false
        for (ch in channels) {
            val v = sample.values[ch.signal.key] ?: continue
            ch.counter++
            if (ch.counter >= ch.decimationStep) {
                ch.counter = 0
                try {
                    ch.writer.write("$isoTs,${sample.timestampMs},${"%.6f".format(v)}\n")
                    ch.rowsWritten++
                    wrote = true
                } catch (_: Exception) {
                    // Writer closed mid-flight (stop race) — ignore silently
                }
            }
        }
        if (wrote) {
            _totalSamplesWritten++
            if (_totalSamplesWritten % 200L == 0L) {
                channels.forEach { runCatching { it.writer.flush() } }
            }
        }
    }

    /** Emergency reset — call if the app detects recording stuck in bad state. */
    fun resetRecordingState() {
        channels.forEach { runCatching { it.writer.close() } }
        channels.clear()
        _isRecording = false
        _totalSamplesWritten = 0L
        AppLog.w("REC", "Recording state forcibly reset")
    }

    // ─── Stop recording ───────────────────────────────────────────────────────
    suspend fun stopRecording(): Result<RecordingSession> = withContext(Dispatchers.IO) {
        _isRecording = false  // Stop writes immediately, even if rest fails
        return@withContext try {
            val endTs = isoFmt.format(Date())
            val files = mutableListOf<RecordingFile>()
            val channelsCopy = channels.toList()  // snapshot before clear
            channels.clear()

            for (ch in channelsCopy) {
                try {
                    ch.writer.write("# Session end: $endTs\n")
                    ch.writer.write("# Rows written: ${ch.rowsWritten}\n")
                    ch.writer.flush()
                    ch.writer.close()
                    if (ch.file.exists() && ch.file.length() > 0) {
                        files.add(RecordingFile(
                            name = ch.file.nameWithoutExtension,
                            path = ch.file.absolutePath,
                            sizeBytes = ch.file.length(),
                            lastModified = ch.file.lastModified(),
                            signalDisplayName = ch.signal.displayName,
                            signalUnit = ch.signal.unit,
                            rateHz = ch.targetHz,
                            sessionId = sessionId,
                            rowCount = ch.rowsWritten
                        ))
                    }
                } catch (e: Exception) {
                    AppLog.e("REC", "Error closing ${ch.signal.key}: ${e.message}")
                }
            }

            val session = RecordingSession(
                sessionId = sessionId,
                deviceName = sessionDir?.name?.substringBeforeLast("_") ?: "Unknown",
                startTimeMs = runCatching {
                    sessionDateFmt.parse(sessionId)?.time ?: 0L
                }.getOrDefault(0L),
                files = files
            )
            AppLog.ok("REC", "Session stopped — ${files.size} files, $_totalSamplesWritten rows")
            Result.success(session)
>>>>>>> parent of 335abb6 (Added position)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // ─── List all recordings ──────────────────────────────────────────────────
    suspend fun listRecordings(): List<RecordingFile> = withContext(Dispatchers.IO) {
        // Search both storage locations:
        // 1. Current location: app-specific external files (getExternalFilesDir)
        // 2. Legacy location: public Downloads used by versions prior to v1.5.x
        val dirs = mutableListOf(getRecordingDir())
        try {
            val legacyDir = java.io.File(
                android.os.Environment.getExternalStoragePublicDirectory(
                    android.os.Environment.DIRECTORY_DOWNLOADS), "ShimmerENACT"
            )
            if (legacyDir.exists() && legacyDir.isDirectory) dirs.add(legacyDir)
        } catch (_: Exception) {}

        dirs.flatMap { dir ->
            dir.listFiles { f -> f.extension == "csv" }?.toList() ?: emptyList()
        }
            .distinctBy { it.absolutePath }
            .sortedByDescending { it.lastModified() }
            .map { f ->
                RecordingFile(
                    name         = f.nameWithoutExtension,
                    path         = f.absolutePath,
                    sizeBytes    = f.length(),
                    lastModified = f.lastModified()
                )
            }
    }

<<<<<<< HEAD
    // ─── Delete a recording ───────────────────────────────────────────────────
    suspend fun deleteRecording(path: String): Boolean = withContext(Dispatchers.IO) {
        File(path).delete()
    }

    // ─── Directory helper ─────────────────────────────────────────────────────
    private fun getRecordingDir(): File {
        val dir = File(
            context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),
            "ShimmerENACT"
        )
        if (!dir.exists()) dir.mkdirs()
        return dir
=======
    // ─── Delete session directory ─────────────────────────────────────────────
    suspend fun deleteSession(sessionId: String): Boolean = withContext(Dispatchers.IO) {
        getRootDir().listFiles { f -> f.isDirectory && f.name.contains(sessionId) }
            ?.firstOrNull()?.deleteRecursively() ?: false
    }

    // ─── Delete single file ───────────────────────────────────────────────────
    suspend fun deleteFile(path: String): Boolean = withContext(Dispatchers.IO) {
        File(path).delete()
    }

    // ─── Storage location ──────────────────────────────────────────────────────
    // Downloads/ShimmerENACT — accessible in any file manager.
    private fun getRootDir(): File {
        val downloads = Environment.getExternalStoragePublicDirectory(
            Environment.DIRECTORY_DOWNLOADS)
        val root = File(downloads, "ShimmerENACT")
        if (!root.exists()) root.mkdirs()
        return root
>>>>>>> parent of 335abb6 (Added position)
    }

    val isRecording: Boolean get() = headerWritten && writer != null
    val currentSampleCount: Long get() = sampleCount
    val currentFilePath: String get() = currentFile?.absolutePath ?: ""
}

data class RecordingFile(
    val name: String,
    val path: String,
    val sizeBytes: Long,
    val lastModified: Long
) {
    val sizeDisplay: String get() = when {
        sizeBytes > 1_048_576 -> "%.1f MB".format(sizeBytes / 1_048_576.0)
        sizeBytes > 1024 -> "%.1f KB".format(sizeBytes / 1024.0)
        else -> "$sizeBytes B"
    }
}

data class RecordingSession(
    val sessionId: String,
    val deviceName: String,
    val startTimeMs: Long,
    val files: List<RecordingFile>
)
